# Generated by Django 6.0.2 on 2026-02-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='time',
        ),
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.IntegerField(default=60),
        ),
    ]
